os: linux
language: php
dist: xenial

cache:
  directories:
    - $HOME/.composer/cache

php:
  - '7.4'
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_install:
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --no-progress --no-suggest -o
  - echo 'error_reporting = E_ALL' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script:
  - cd tests && php -dshort_open_tag=Off -dmagic_quotes_gpc=Off index.php
