name: Static Analysis

on:
    push:
        paths-ignore:
            - 'docs/**'
    pull_request:
        paths-ignore:
            - 'docs/**'

jobs:
    static-analysis-psalm:
        name: "Psalm"
        runs-on: "ubuntu-latest"

        strategy:
            matrix:
                php-version:
                    - "7.4"

        steps:
            - name: "Checkout code"
              uses: "actions/checkout@v2"

            - name: "Install PHP"
              uses: "shivammathur/setup-php@v2"
              with:
                  coverage: "none"
                  php-version: "${{ matrix.php-version }}"
                  extensions: "intl, json, pdo, bcmath, imagick"

            - name: "Install dependencies with Composer"
              uses: "ramsey/composer-install@v1"

            - name: "Run a static analysis with vimeo/psalm"
              run: "vendor/bin/psalm --show-info=false --stats --output-format=github --threads=$(nproc)"
